# Generated by Django 3.1 on 2020-08-30 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='index',
            options={'ordering': ['-dob']},
        ),
    ]
