# Generated by Django 3.1 on 2020-08-30 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200830_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='index',
            name='phone_number',
            field=models.CharField(default=0, max_length=14),
            preserve_default=False,
        ),
    ]
