# Generated by Django 3.1 on 2020-08-30 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_index_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='index',
            name='contact_id',
            field=models.CharField(default='Self', max_length=255),
            preserve_default=False,
        ),
    ]
